### ISSUE TITLE
How to use the edited file correctly

### ISSUE THREAD

**Issue by LiYifan985** [JohannesKrueger/pointcloudeditor#3]
Dear developer, I exported the edited txt file using your editor and found that I can't use it for 3DGS rebuild, it always reports an error, can you tell me how to rebuild the edited scene correctly?

**Comment by JohannesKrueger** [comment]
Thanks for the message, the downloaded .txt files should be read by the COLMAP script used in 3DGS. Could you please send me your downloaded files so I can fix the error? 
Could it perhaps be because you forgot to import the cameras.txt / cameras.bin file when using 3DGS? Thanks!

**Comment by LiYifan985** [comment]
Thank you very much for getting back to me, and I would appreciate it if you could guide me on the next steps. I exported the txt file manually in colmap, edited it in your editor, downloaded modifiedPoints3D.txt and modifiedimages.txt, renamed and replaced the original txt file, exported the bin file using the command ‘python convert.py -s $FOLDER_PATH ---skip_matching' to output the bin file, and then rebuilt it, and found that the scene is still the same as before editing.
With regard to the cameras.txt file, no changes or replacements were made.

**Comment by LiYifan985** [comment]
Your tool, if realised successfully, can help me immensely in my studies and research, thank you again!

**Comment by JohannesKrueger** [comment]
Hello, thank you for the information. I just recorded a Video on how to use the Pointcloudeditor, hopefully this helps: 
[Youtube Link](https://www.youtube.com/watch?v=A7QSRSUuIW4)

**Comment by LiYifan985** [comment]
I'm sorry to keep bothering you, I appreciate your videos and the work you put into my problem.My ultimate goal with your project is to speed up the training of 3DGS in the face of large scenes by removing unnecessary parts before training. I followed every step of the video you posted and had no problems up to the cutoff of your video. But when I trained the edited files, I found that the reconstructed scene (3DGS)was still the original. Found that the COLMAP output points3D.ply was not changed (I found this by checking the file size), so I manually exported the new ply file, but it reported the following error:(3DGStream) PS F:\GS+\3DGStream1> python train.py -s .\data\test2\ -m output/test7
Optimizing output/test7
Output folder: output/test7 [14/10 20:32:33]
Tensorboard not available: not logging progress [14/10 20:32:33]
Reading camera 53/53 [14/10 20:32:33]
Loading Training Cameras [14/10 20:32:33]
Loading Test Cameras [14/10 20:32:36]
Traceback (most recent call last):
  File "train.py", line 219, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 35, in training
    scene = Scene(dataset, gaussians)
  File "F:\GS+\3DGStream1\scene\__init__.py", line 83, in __init__
    self.gaussians.create_from_pcd(scene_info.point_cloud, self.cameras_extent)
  File "F:\GS+\3DGStream1\scene\gaussian_model.py", line 126, in create_from_pcd
    fused_point_cloud = torch.tensor(np.asarray(pcd.points)).float().cuda()
AttributeError: 'NoneType' object has no attribute 'points'

**Comment by LiYifan985** [comment]
As a beginner, my questions may seem extremely naive and I'm sorry to keep bothering you, if you agree I would like to put you in the thank you at the end of my paper!

**Comment by JohannesKrueger** [comment]
Hello, sorry for the late reply. Please make sure if you have already trained with the dataset in 3D Gaussian Splatting to delete the created "Points3D.ply" file. If this is not deleted, the modified images.txt & points3D.txt have no influence and are ignored. This file must always be created anew at the beginning of the script using the points3d.txt file.

Unfortunately I couldn't reproduce the error that happened in the training script. The modified files work perfectly for me.

If that doesn't work, it would be nice if you could send me your dataset so that I can test it and, if necessary, fix the error in the code.

**Comment by LiYifan985** [comment]
Thank you so much for your willingness to continue to reply to my messages, I will send you my file, it's just a simple test file, feel free to change it to any other test pre-training edited object, I'm trying to figure out how I can make the 3DGS train out of the changed scene, and I'd like to see a video walkthrough of you training the file, or manipulating it, in the 3DGS, if that's possible.
[test.zip](https://github.com/user-attachments/files/17476917/test.zip)

**Comment by JohannesKrueger** [comment]
Hello, attached is a short video in which I go through all the steps with the dataset sent. I hope this solves the problems. Link: https://drive.google.com/file/d/1hednIJ3E7E7RGVn6qpzS2v9ivvpHpsU2/view?usp=sharing

**Comment by LiYifan985** [comment]
[queastion.zip](https://github.com/user-attachments/files/17483928/queastion.zip)
Thank you for going out of your way to provide guidance, you are a god to me. The problem with my point cloud appeared in the second half and recorded the thing as a video and sent it to you. It's in the zip below and I'm sure your skills will have a great impact on 3DGS technology.
